find_nearest_stations:
  name: "Trouver les stations proches"
  description: "Trouver les stations proches les moins chères"
  fields:
    entity_id:
      name: Entité
      description: Entité possédant une localisation
      required: true
      example: person.me
      selector:
        entity:
    fuel:
      name: Carburant
      description: Le type de carburant
      required: true
      advanced: false
      example: "E10"
      selector:
        select:
          options:
            - "Gazole"
            - "SP95"
            - "SP98"
            - "E10"
            - "E85"
            - "GPLc"
    distance:
      name: Distance maximum
      description: Distance maximum entre les stations et l'entité
      required: true
      default: 10
      selector:
        number:
          min: 1
          max: 30
