name: Validate Stations JSON

on:
  pull_request:
    paths:
      - "custom_components/prix_carburant/stations_name.json"

jobs:
  validate-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Make validation script executable
        run: chmod +x scripts/validate_stations.py

      - name: Validate stations_name.json
        id: validate-json
        run: |
          echo "Validating stations_name.json file..."
          python scripts/validate_stations.py custom_components/prix_carburant/stations_name.json
          if [ $? -eq 0 ]; then
            echo "JSON is valid"
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "JSON is invalid"
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Check if PR only modifies stations_name.json
        id: check-pr-files
        if: steps.validate-json.outputs.valid == 'true'
        uses: dorny/paths-filter@v3
        with:
          filters: |
            stations_only:
              - 'custom_components/prix_carburant/stations_name.json'

      - name: Auto-approve PR
        if: steps.check-pr-files.outputs.stations_only == 'true'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.check-pr-files.outputs.stations_only == 'true'
        run: |
          gh pr merge --auto --merge "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
